wandb_version: 1

batch_size:
  desc: null
  value: 128
linear:
  desc: null
  value:
  - 784
  - 196
  - 196
  - 196
  - 10
device:
  desc: null
  value: cuda
epochs:
  desc: null
  value: 150
optim:
  desc: null
  value: torch.optim.SGD
optim_config:
  desc: null
  value:
    lr: 0.001
    momentum: 0.9
lossfn:
  desc: null
  value: CrossEntropyLoss()
project:
  desc: null
  value: python-CourseDesign
wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.10.11
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687191428.049779
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.2
      8:
      - 3
      - 5
